
import java.rmi.RemoteException;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author mtzcpd258
 */
public class TelaEditaContato extends javax.swing.JPanel {

    /**
     * Creates new form TelaContato
     */
    public TelaEditaContato() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jEmail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jAniversario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("Nome");

        jLabel2.setText("Email");

        jButton1.setText("Atualizar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atualizarContatoNoCliqueDoMouse(evt);
            }
        });

        jButton2.setText("Remover");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removerContatoNoCliqueDoMouse(evt);
            }
        });

        jLabel3.setText("Aniversario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jAniversario, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jNome, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jEmail)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 158, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAniversario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(0, 14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarContatoNoCliqueDoMouse(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atualizarContatoNoCliqueDoMouse
        if (jNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nao foi possivel executar esta operacao, "
                    + "pois o campo nome esta nulo", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (jEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nao foi possivel executar esta operacao, "
                    + "pois o campo email esta nulo", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (jAniversario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nao foi possivel executar esta operacao, "
                    + "pois o campo aniversario esta nulo", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        contato.setNome(jNome.getText());
        contato.setDtAniversario(jAniversario.getText());
        contato.setEmail(jEmail.getText());
        
        try {
            
            client.atualizarContato(contato);
            
            //jNome.setText(null);
            //jEmail.setText(null);
            //jAniversario.setText(null);
            
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(null, "Houve um erro no momento de atualizar o Contato", 
                    "Erro", JOptionPane.ERROR_MESSAGE);
            
            ex.printStackTrace();
        }
    }//GEN-LAST:event_atualizarContatoNoCliqueDoMouse

    private void removerContatoNoCliqueDoMouse(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removerContatoNoCliqueDoMouse
        if (contato == null) {
            JOptionPane.showMessageDialog(null, "Nao foi possivel executar esta operacao, "
                    + "pois o contato esta nulo", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            
            client.removerContato(contato);
            telaPesquisar.avisarRemocao(contato);
            
            jNome.setText(null);
            jEmail.setText(null);
            jAniversario.setText(null);
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(null, "Houve um erro no momento de remover o Contato", 
                    "Erro", JOptionPane.ERROR_MESSAGE);
            
            ex.printStackTrace();
        }
    }//GEN-LAST:event_removerContatoNoCliqueDoMouse

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAniversario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jNome;
    // End of variables declaration//GEN-END:variables
    private AgendaClient client;
    private Contato contato;
    private TelaPesquisar telaPesquisar;
    
    public void adicionarClient(AgendaClient client) {
        this.client = client;
    }
    
    public void adicionarContatoNaTela(Contato contatoParm) {
        this.contato = contatoParm;
        jNome.setText(contato.getNome());
        jAniversario.setText(contato.getDtAniversario());
        jEmail.setText(contato.getEmail());
    }
    
    public void adicionaTelaPesquisaContato(TelaPesquisar telaPesquisar) {
        this.telaPesquisar = telaPesquisar;
    }
}
