/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


import java.rmi.RemoteException;
import javax.swing.JOptionPane;

/**
 *
 * @author rafaeuoliveira
 */
public class TelaNovoContato extends javax.swing.JPanel {

    /**
     * Creates new form TelaNovoContato
     */
    public TelaNovoContato() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jAniversario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jEmail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Nome");

        jLabel2.setText("Nascimento");

        jLabel3.setText("Email");

        jButton1.setText("Salvar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salvarNoCliqueDoMouse(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jEmail)
            .add(jNome)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(0, 293, Short.MAX_VALUE)
                .add(jButton1))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jAniversario)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(3, 3, 3)
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(3, 3, 3)
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(4, 4, 4)
                        .add(jLabel3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(14, 14, 14)
                .add(jLabel1)
                .add(4, 4, 4)
                .add(jNome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(20, 20, 20)
                .add(jLabel2)
                .add(4, 4, 4)
                .add(jAniversario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(27, 27, 27)
                .add(jLabel3)
                .add(3, 3, 3)
                .add(jEmail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void salvarNoCliqueDoMouse(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarNoCliqueDoMouse
        if (jNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nao foi possivel executar esta operacao, "
                    + "pois o campo nome esta nulo", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        if (jEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nao foi possivel executar esta operacao, "
                    + "pois o campo email esta nulo", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        if (jAniversario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nao foi possivel executar esta operacao, "
                    + "pois o campo aniversario esta nulo", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
        contato = new Contato();
        contato.setNome(jNome.getText());
        contato.setDtAniversario(jAniversario.getText());
        contato.setEmail(jEmail.getText());
        
        try {
            client.inserirNovoContato(contato);
            
            JOptionPane.showMessageDialog(null, "Contato "+contato.getNome()+ 
                    " gravado com sucesso!", "Informaçao", JOptionPane.INFORMATION_MESSAGE);
            
            //limpar os campos da tela
            jNome.setText(null);
            jAniversario.setText(null);
            jEmail.setText(null);
            
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(null, "Houve um erro no momento de salvar o Contato", 
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_salvarNoCliqueDoMouse

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAniversario;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jNome;
    // End of variables declaration//GEN-END:variables
    private AgendaClient client;
    private Contato contato;
    
    public void adicionarClient(AgendaClient client) {
        this.client = client;
    }
}
