/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


//<editor-fold defaultstate="collapsed" desc="comment">
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.rmi.RemoteException;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author mtzcpd258
 */
public class TelaPesquisar extends javax.swing.JPanel {

    /**
     * Creates new form TelaCadastro
     */
    public TelaPesquisar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setLayout(new java.awt.CardLayout());

        jLabel1.setText("Pesquisar");

        jButton1.setText("Buscar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesquisarNoCliqueDoMouse(evt);
            }
        });

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisarNoCliqueDoMouse(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisarNoCliqueDoMouse
        String termoBusca = jTextField1.getText();
        try {
            contatosResult = client.pesquisarContato(termoBusca);
            listModel = new DefaultListModel();
            
            for (Contato jContato : contatosResult) {
                listModel.addElement(jContato.getNome());
            }
            jList1.setModel(listModel);
            
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(null, "Houve um erro no momento de pesquisar os Contatos", 
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
        
        jList1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent me) {
                if (me.getClickCount() == 2) {
                    int index = jList1.getSelectedIndex();
                    contato = contatosResult.get(index);
                    telaEditaContato.adicionarContatoNaTela(contato);
                }
            }
        });
    }//GEN-LAST:event_pesquisarNoCliqueDoMouse

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    private DefaultListModel listModel;
    private AgendaClient client;
    private Contato contato;
    private List<Contato> contatosResult;
    private TelaEditaContato telaEditaContato;
    
    
    public void adicionarClient(AgendaClient client) {
        this.client = client;
    }
    
    public void adicionaTelaEditaContato(TelaEditaContato telaEditaContato) {
        this.telaEditaContato = telaEditaContato;
    }

    public void avisarRemocao(Contato contatoParam) {
        listModel = new DefaultListModel();
        
        contatosResult.remove(contatoParam);
        
        for (Contato jContato : contatosResult) {
            listModel.addElement(jContato.getNome());
        }
        jList1.setModel(listModel);
    }
}
